spring:














  main:
    allow-bean-definition-overriding: true
      
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 520246547843-m73spml2vj739s0h1s4s1ug0btojuqf3.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile
         facebook:
             clientId: 0fd9c731e85c4f8401f8
             clientSecret: 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
             scope:
                   - email
                   - Public_profile 
         github:
             clientId: 0fd9c731e85c4f8401f8
             clientSecret: b90598148c19b4aeb9c684c84d41dce374741a4b
             scope:
                   - email
                   - Public_profile
                   - user_birthday
                   - user_photos 
           
           
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp        
      
server:
  servlet:
    context-path: /ProductManager      